drop table if exists USER_COSTS;
drop table if exists USER_GROUPS_RECEIPT_TYPES;
drop table if exists RECEIPT_TYPES;
drop table if exists REIMBURSEMENTS;
drop table if exists USERS;
drop table if exists USER_GROUPS;

create table USER_GROUPS (
                             id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                             name varchar(100) not null,
                             daily_allowance DOUBLE DEFAULT (0.0),
                             cost_per_km     DOUBLE DEFAULT (0.0),
                             max_mileage     DOUBLE DEFAULT (0.0),
                             max_refund      DOUBLE DEFAULT (0.0)
);
create table USERS (
                       id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                       name varchar(100) not null ,
                       user_group_id int null,
                       foreign key (user_group_id) references USER_GROUPS (id)
);
create table REIMBURSEMENTS(
                               id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                               name varchar(100) not null,
                               start_date date default null,
                               end_date date not null,
                               distance int default 0.00,
                               pushed_to_accept bit default false,
                               user_id int not null ,
                               foreign key (user_id) references USERS (id)
);
CREATE TABLE RECEIPT_TYPES (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,
                            max_value DECIMAL(10,2) DEFAULT 0 NOT NULL
);
create table USER_GROUPS_RECEIPT_TYPES (
                                           user_group_id int not null,
                                           receipt_type_id int not null,
                                           primary key (user_group_id, receipt_type_id),
                                           foreign key (user_group_id) references USER_GROUPS (id),
                                           foreign key (receipt_type_id) references RECEIPT_TYPES(id)
);
CREATE TABLE USER_COSTS (id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                         name VARCHAR(100) NOT NULL,
                         cost_value DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
                         receipt_type_id int not null,
                         foreign key (receipt_type_id) references RECEIPT_TYPES (id),
                         reimbursement_id int not null,
                         foreign key (reimbursement_id) references REIMBURSEMENTS (id)
);

insert into USER_GROUPS (name) values
                                  ('CEO'),
                                  ('Sellers'),
                                  ('Regular employee'),
                                  ('Office employee')
;
insert into RECEIPT_TYPES (name, max_value) values
                                  ('Train_AllUsers', 100),
                                  ('Aeroplane_CEO', 2000),
                                  ('Food_AllUsers', 45),
                                  ('Food_CEO', 450),
                                  ('Hotels_Sellers', 450),
                                  ('Other_Directors', 450)
;
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (1,1);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (2,1);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (3,1);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (4,1);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (1,2);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (1,3);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (2,3);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (3,3);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (4,3);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (1,4);
insert into USER_GROUPS_RECEIPT_TYPES (user_group_id, receipt_type_id) values (2,5);