create table USERS(
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar(100) not null,
                      user_group_id int null,
                      foreign key (user_group_id) references USER_GROUPS (id)
);