create table REIMBURSEMENTS(
                              id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
                              name varchar(100) not null,
                              start_date date default null,
                              end_date date not null,
                              distance int default 0,
                              pushed_to_accept bit default false,
                              user_id int not null ,
                              foreign key (user_id) references USERS (id)
);